beginners:
 motivation:
  question: "Why do you want to be a part of Learn IT Girl? Tell us about your motivation!"
  max_score: "5"
  answers:
  - answer: "Their love for coding - have stated some examples of previous learning experience"
    hint: "If they say they enjoy coding and have been spending time learning how to code using different sources"
    score: "5"
  - answer: "Wish to change the current profession with programming"
    hint: "If they want to change thei current profession with programming, but have already tried exploring the IT field"
    score: "5"
  - answer: "Wish to apply their knowledge and network"
    hint: "If they want to apply their knowledge or extend their understanding by working on a practical project and interact with peoople who share their interests"
    score: "4"
  - answer: "Wish to learn a new language and explore the IT field"
    hint: "If they are already experienced in some programming language and want to learn another one and explore the field"
    score: "5"
  - answer: "Their love for coding - no specific explanation"
    hint: "If they say they enjoy coding, but don't state any specific example or learning experience"
    score: "3"
  - answer: "Want to teach others"
    hint: "They want to learn coding in order to be able to teach others (professionally)"
    score: "2"
  - answer: "They provide generic reasons or state that the future is in programming"
    hint: "They don't give ANY personal reasons, only some generic statements like 'it is the language of the future'"
    score: "0"
  - answer: "Wish to learn, but need to be PUSHED by the mentor"
    hint: "If they say they want to learn, but their main motivation is having a mentor instead of learning the language"
    score: "1"
  - answer: "A newbee/beginner says she wishes to learn to code, but need to be GUIDED by mentor"
    hint: "A beginner, that wants to learn, but is too shy or does not know anybody to ask for help. Feel that a mentor is a save person to guide them on their first steps."
    score: "3"
  - answer: "Discover if programming is the right thing for them"
    hint: "If they're clearly not into programming, but have heard that it is cool and profitable and just want to try it out"
    score: "1"
  - answer: "They state conflicting or unrelated reasons"
    hint: "If they say they want to improve their English or pass an exam, or give conflicting statements"
    score: "0"
 creativity:
  question: "What project would you like to develop during the program?"
  max_score: "5"
  answers:
  - answer: "They give unique and creative project proposal"
    hint: "The project proposal they provide is thought through, different than the standard proposals and not mentioned in the example"
    score: "5"
  - answer: "They give a short overview of their idea"
    hint: "The project proposal is not very detailed, but the idea is feasible and individual"
    score: "4"
  - answer: "They don't have a specific idea, but know what they want to build in a higher level"
    hint: "They don't give a project proposal, but know what kind of application want to implement (mobile app for example)"
    score: "3"
  - answer: "They only state the technology they want to use, not the project idea"
    hint: "They mention the technology or language they want to use, but don't give a specific project proposal"
    score: "2"
  - answer: "They give a modified version of a copied project idea"
    hint: "They propose to build some project from a tutorial or online resource, with a few modifications or individual tweaks."
    score: "2"
  - answer: "They give a copied project idea"
    hint: "They copy the example project proposal from last editions or make only slight modifications to it"
    score: "0"
  - answer: "They don't give any idea"
    hint: "They don't give a project proposal stating they are beginners"
    score: "0"
 teamwork_leadership:
   teamwork:
    question: "Tell us about a time where you collaborated with others in a team. What was the project or task that you worked on? What was your role in the team? How was your experience? This does not have to be in a technical job or project - we just want to get to know you as a teamplayer."
    max_score: "2"
    answers:
    - answer: "They share their experience and explain their role"
      hint: "They give at least one complete example about teamwork and their role"
      score: "2"
    - answer: "They share their experience, but don't tell their role"
      hint: "They give one or several examples of their previous experience, but don't mention their role in it"
      score: "1"
    - answer: "Incomplete or short answer / No experience"
      hint: "If they give an incomplete answer or finish it in one sentence or two, or they say they have no experience"
      score: "0"
   leadership:
    question: "If you get accepted at Learn IT, Girl!, you have 12 weeks to implement your project idea. What would be your roadmap to achieve this?"
    max_score: "5"
    answers:
    - answer: "They provide steps that can help them reach their goals"
      hint: "If they describe the roadmap in details and provide steps that will be able to follow in order to reach their goals"
      score: "5"
    - answer: "They provide only basic info, with no detailed steps"
      hint: "If they give some general overview of their roadmap, without detailed steps or logical order, but relate it to their project idea"
      score: "4"
    - answer: "They give a generic roadmap that could be applied to any project"
      hint: "If they give some general steps, but nothing specific for their project. Example: learn, implement, test etc."
      score: "3"
    - answer: "They don't provide any roadmap"
      hint: "If they say they don't know it yet, or that it will be done with mentor guidance."
      score: "0"
    - answer: "They explain their application once again"
      hint: "If instead of giving a roadmap, they explain what their application would do all over again."
      score: "0"
    - answer: "They have provided a copied roadmap"
      hint: "If it feels like their roadmap is copied from some project. Example: it contains steps of marketing and deployment, or others which don’t actually belong there."
      score: "0"
 soundness:
  question: ""
  max_score: "2"
  answers:
  - answer: "They overestimated the time they can dedicate on the program"
    hint: "If they state they can put in more than 7 hours of work, even though they have a job/school and/or other responsibilities which involves them full time"
    score: "1"
  - answer: "They say they are beginners, but you can state the oposite"
    hint: "If they state they are beginners, but you can tell from their application that they are not"
    score: "1"
 dedication:
  question: ""
  max_score: "1"
  answers:
  - answer: "The application is well prepared, answers are very detailed and it shows a lot of motivation on the side of the mentee"
    hint: "If you feel the application should be promoted you can award an extra point here."
    score: "1"
  - answer: "The application very brief and looks like it has been completed in 5 minutes."
    hint: "If eventhough it is a complete application, it contains mostly super short answers. This option subtracts one point from their score."
    score: "-1"
experienced:
 motivation:
  question: "Why do you want to be a part of Learn IT Girl? Tell us about your motivation!"
  max_score: "5"
  answers:
  - answer: "Their love for coding - have stated some examples of previous learning experience"
    hint: "If they say they enjoy coding and have been spending time learning how to code using different sources"
    score: "5"
  - answer: "Wish to change the current profession with programming"
    hint: "If they want to change thei current profession with programming, but have already tried exploring the IT field"
    score: "5"
  - answer: "Wish to apply their knowledge and network"
    hint: "If they want to apply their knowledge or extend their understanding by working on a practical project and interact with peoople who share their interests"
    score: "4"
  - answer: "Wish to learn a new language and explore the IT field"
    hint: "If they are already experienced in some programming language and want to learn another one and explore the field"
    score: "5"
  - answer: "Their love for coding - no specific explanation"
    hint: "If they say they enjoy coding, but don't state any specific example or learning experience"
    score: "3"
  - answer: "Want to teach others"
    hint: "They want to learn coding in order to be able to teach others (professionally)"
    score: "2"
  - answer: "They provide generic reasons or state that the future is in programming"
    hint: "They don't give ANY personal reasons, only some generic statements like 'it is the language of the future'"
    score: "0"
  - answer: "Wish to learn, but need to be PUSHED by the mentor"
    hint: "If they say they want to learn, but their main motivation is having a mentor instead of learning the language"
    score: "1"
  - answer: "A newbee/beginner says she wishes to learn to code, but need to be GUIDED by mentor"
    hint: "A beginner, that wants to learn, but is too shy or does not know anybody to ask for help. Feel that a mentor is a save person to guide them on their first steps."
    score: "3"
  - answer: "Discover if programming is the right thing for them"
    hint: "If they're clearly not into programming, but have heard that it is cool and profitable and just want to try it out"
    score: "1"
  - answer: "They state conflicting or unrelated reasons"
    hint: "If they say they want to improve their English or pass an exam, or give conflicting statements"
    score: "0"
 creativity:
  question: "What project would you like to develop during the program?"
  max_score: "5"
  answers:
  - answer: "They give unique and creative project proposal"
    hint: "The project proposal they provide is thought through, different than the standard proposals and not mentioned in the example"
    score: "5"
  - answer: "They give a short overview of their idea"
    hint: "The project proposal is not very detailed, but the idea is feasible and individual"
    score: "4"
  - answer: "They don't have a specific idea, but know what they want to build in a higher level"
    hint: "They don't give a project proposal, but know what kind of application want to implement (mobile app for example)"
    score: "3"
  - answer: "They only state the technology they want to use, not the project idea"
    hint: "They mention the technology or language they want to use, but don't give a specific project proposal"
    score: "2"
  - answer: "They give a modified version of a copied project idea"
    hint: "They propose to build some project from a tutorial or online resource, with a few modifications or individual tweaks."
    score: "2"
  - answer: "They give a copied project idea"
    hint: "They copy the example project proposal from last editions or make only slight modifications to it"
    score: "0"
  - answer: "They don't give any idea"
    hint: "They don't give a project proposal stating they are beginners"
    score: "0"
 teamwork_leadership:
   teamwork:
    question: "Tell us about a time where you collaborated with others in a team. What was the project or task that you worked on? What was your role in the team? How was your experience? This does not have to be in a technical job or project - we just want to get to know you as a teamplayer."
    max_score: "2"
    answers:
    - answer: "They share their experience and explain their role"
      hint: "They give at least one complete example about teamwork and their role"
      score: "2"
    - answer: "They share their experience, but don't tell their role"
      hint: "They give one or several examples of their previous experience, but don't mention their role in it"
      score: "1"
    - answer: "Incomplete or short answer / No experience"
      hint: "If they give an incomplete answer or finish it in one sentence or two, or they say they have no experience"
      score: "0"
   leadership:
    question: "If you get accepted at Learn IT, Girl!, you have 12 weeks to implement your project idea. What would be your roadmap to achieve this?"
    max_score: "5"
    answers:
    - answer: "They provide steps that can help them reach their goals"
      hint: "If they describe the roadmap in details and provide steps that will be able to follow in order to reach their goals"
      score: "5"
    - answer: "They provide only basic info, with no detailed steps"
      hint: "If they give some general overview of their roadmap, without detailed steps or logical order, but relate it to their project idea"
      score: "4"
    - answer: "They give a generic roadmap that could be applied to any project"
      hint: "If they give some general steps, but nothing specific for their project. Example: learn, implement, test etc."
      score: "3"
    - answer: "They don't provide any roadmap"
      hint: "If they say they don't know it yet, or that it will be done with mentor guidance."
      score: "0"
    - answer: "They explain their application once again"
      hint: "If instead of giving a roadmap, they explain what their application would do all over again."
      score: "0"
    - answer: "They have provided a copied roadmap"
      hint: "If it feels like their roadmap is copied from some project. Example: it contains steps of marketing and deployment, or others which don’t actually belong there."
      score: "0"
 experience:
  question: "Do you have previous experience in any other programming language? Please name the language(s), your level of expertise (beginner, intermediate, professional) and tell us about the projects you have worked on."
  max_score: "2"
  answers:
  - answer: "They have completed a project"
    hint: "If they have completed a project on their own or as part of GSOC, google code in, or in a group and did a meaningful part of it"
    score: "2"
  - answer: "They mention some project they have worked on, without explaining their role"
    hint: "If the scholar shares her previous experience without giving any specifics of what her role was in it"
    score: "1"
  - answer: "They only provide a github/blog link"
    hint: "They don't give any description of their previous experience, only share a link of their github profile or blog"
    score: "1"
  - answer: "Too many languages with no specified experience"
    hint: "If they mention too many laguages, with no projects listed to cover that."
    score: "0"
  - answer: "Described projects were never completed"
    hint: "If you find out that the described projects were never completed"
    score: "0"
 soundness:
  question: ""
  max_score: "2"
  answers:
  - answer: "They overestimated the time they can dedicate on the program"
    hint: "If they state they can put in more than 7 hours of work, even though they have a job/school and/or other responsibilities which involves them full time"
    score: "1"
  - answer: "They hide their real experience"
    hint: "If they state they don't know some language confidently, but you can tell from their application that they should"
    score: "1"
 dedication:
  question: ""
  max_score: "1"
  answers:
  - answer: "The application is well prepared, answers are very detailed and it shows a lot of motivation on the side of the mentee"
    hint: "If you feel the application should be promoted you can award an extra point here."
    score: "1"
  - answer: "The application very brief and looks like it has been completed in 5 minutes."
    hint: "If eventhough it is a complete application, it contains mostly super short answers. This option subtracts one point from their score."
    score: "-1"
