beginners:
 motivation:
  question: "What motivated you to become a scholar?"
  max_score: "3"
  answers:
  - answer: "Their love for coding - have stated some examples of previous learning experience"
    hint: "If they say they enjoy coding and have been spending time learning how to code using different sources"
    score: "3"
  - answer: "Wish to change the current profession with programming"
    hint: "If they want to change thei current profession with programming, but have already tried exploring the IT field"
    score: "3"
  - answer: "Wish to apply their knowledge and network"
    hint: "If they want to apply their knowledge or extend their understanding by working on a practical project and interact with peoople who share their interests"
    score: "3"
  - answer: "Wish to learn a new language and explore the IT field"
    hint: "If they are already experienced in some programming language and want to learn another one and explore the field"
    score: "3"
  - answer: "Their love for coding - no specific explanation"
    hint: "If they say they enjoy coding, but don't state any specific example or learning experience"
    score: "2"
  - answer: "Want to teach others"
    hint: "They want to learn coding in order to be able to teach others (professionally)"
    score: "2"
  - answer: "They provide generic reasons or state that the future is in programming"
    hint: "They don't give any personal reasons, only some generic statements like 'it is the language of the future'"
    score: "0"
  - answer: "Wish to learn, but need to be pushed by the mentor"
    hint: "If they say they want to learn, but their main motivation is having a mentor instead of learning the language"
    score: "0"
  - answer: "Discover if programming is the right thing for them"
    hint: "If they're clearly not into programming, but have heard that it is cool and profitable and just want to try it out"
    score: "0"
  - answer: "They state conflicting or unrelated reasons"
    hint: "If they say they want to improve their English or pass an exam, or give conflicting statements"
    score: "0"
 creativity:
  question: "Which project would you like to develop during the program?"
  max_score: "2"
  answers:
  - answer: "They give unique and creative project proposal"
    hint: "The project proposal they provide is thought through, different than the standard proposals and not mentioned in the example"
    score: "2"
  - answer: "They give a short overview of their idea"
    hint: "The project proposal is not very detailed, or the idea is not feasible"
    score: "2"
  - answer: "They don't have a specific idea, but know what they want to build in a higher level"
    hint: "They don't give a project proposal, but know what kind of application want to implement (mobile app for example)"
    score: "1"
  - answer: "They only state the technology they want to use, not the project idea"
    hint: "They mention the technology or language they want to use, but don't give a specific project proposal"
    score: "1"
  - answer: "They give a copied project idea"
    hint: "They copy the example project proposal or make slight modifications to it"
    score: "0"
  - answer: "They don't give any idea"
    hint: "They don't give a project proposal stating they are beginners"
    score: "0"
 teamwork_leadership:
   teamwork:
    question: "Do you have experience working with a team or collaborating with others? Tell us about it. What was the project or task? What was your role? Tell us as many things you want."
    max_score: "2"
    answers: 
    - answer: "They share their experience and explain their role"
      hint: "They give at least one complete example about teamwork and their role"
      score: "2"
    - answer: "They share their experience, but don't tell their role"
      hint: "They give one or several examples of their previous experience, but don't mention their role in it"
      score: "1"
    - answer: "Incomplete or short answer / No experience"
      hint: "If they give an incomplete answer or finish it in one sentence or two, or they say they have no experience"
      score: "0"
   leadership:
    question: "If you were to implement the application described in the previous question, what would be your roadmap?"
    max_score: "3"
    answers:
    - answer: "They provide steps that can help them reach their goals"
      hint: "If they describe the roadmap in details and provide steps that will be able to follow in order to reach their goals"
      score: "3"
    - answer: "They provide only basic info, with no detailed steps"
      hint: "If they give some general overview of their roadmap, without detailed steps or logical order"
      score: "3"
    - answer: "They give a generic roadmap that could be applied to any project"
      hint: "If they give some general steps, but nothing specific for their project. Example: learn, implement, test etc."
      score: "2"
    - answer: "They don't provide any roadmap"
      hint: "If they say they don't know it yet, or that it will be done with mentor guidance."
      score: "0"
    - answer: "They explain their application once again"
      hint: "If instead of giving a roadmap, they explain what their application would do all over again."
      score: "0"
    - answer: "They have provided a copied roadmap"
      hint: "If it feels like their roadmap is copied from some project. Example: it contains steps of marketing and deployment, or others which don’t actually belong there."
      score: "0"
 soundness:
  question: ""
  max_score: "2"
  answers:
  - answer: "They overestimated the time they can dedicate on the program"
    hint: "If they state they can put in more than 7 hours of work, even though they have a job/school and/or other responsibilities which involves them full time"
    score: "1"
  - answer: "They say they are beginners, but you can state the oposite"
    hint: "If they state they are beginners, but you can tell from their application that they are not"
    score: "1"
experienced:
 motivation:
   question: "What motivated you to become a scholar?"
   max_score: "3"
   answers:
   - answer: "Their love for coding - have stated some examples of previous learning experience"
     hint: "If they say they enjoy coding and have been spending time learning how to code using different sources"
     score: "3"
   - answer: "Wish to change the current profession with programming"
     hint: "If they want to change thei current profession with programming, but have already tried exploring the IT field"
     score: "3"
   - answer: "Wish to apply their knowledge and network"
     hint: "If they want to apply their knowledge or extend their understanding by working on a practical project and interact with peoople who share their interests"
     score: "3"
   - answer: "Wish to learn a new language and explore the IT field"
     hint: "If they are already experienced in some programming language and want to learn another one and explore the field"
     score: "3"
   - answer: "Their love for coding - no specific explanation"
     hint: "If they say they enjoy coding, but don't state any specific example or learning experience"
     score: "2"
   - answer: "Want to teach others"
     hint: "They want to learn coding in order to be able to teach others (professionally)"
     score: "2"
   - answer: "They provide generic reasons or state that the future is in programming"
     hint: "They don't give any personal reasons, only some generic statements like 'it is the language of the future'"
     score: "0"
   - answer: "Wish to learn, but need to be pushed by the mentor"
     hint: "If they say they want to learn, but their main motivation is having a mentor instead of learning the language"
     score: "0"
   - answer: "Discover if programming is the right thing for them"
     hint: "If they're clearly not into programming, but have heard that it is cool and profitable and just want to try it out"
     score: "0"
   - answer: "They state conflicting or unrelated reasons"
     hint: "If they say they want to improve their English or pass an exam, or give conflicting statements"
     score: "0"
 creativity:
  question: "Which project would you like to develop during the program?"
  max_score: "2"
  answers:
  - answer: "They give unique and creative project proposal"
    hint: "The project proposal they provide is thought through, different than the standard proposals and not mentioned in the example"
    score: "2"
  - answer: "They give a detailed, feasible idea"
    hint: "If their idea is detailed, thought through and can be implemented"
    score: "2"
  - answer: "They don't have a specific idea, but know what they want to build in a higher level"
    hint: "They don't give a project proposal, but know what kind of application want to implement (mobile app for example)"
    score: "1"
  - answer: "They only state the technology they want to use, not the project idea"
    hint: "They mention the technology or language they want to use, but don't give a specific project proposal"
    score: "1"
  - answer: "They give overview of the idea"
    hint: "Their idea is not described in details, but a general overview is given"
    score: "1"
  - answer: "Not feasible idea"
    hint: "Their idea is well described, but not feasible"
    score: "1"
  - answer: "They give a copied project idea"
    hint: "They copy the example project proposal or make slight modifications to it"
    score: "0"
  - answer: "They don't give any idea"
    hint: "They don't give a project proposal stating they are beginners"
    score: "0"
 teamwork_leadership:
   teamwork:
    question: "Do you have experience working with a team or collaborating with others? Tell us about it. What was the project or task? What was your role? Tell us as many things you want."
    max_score: "2"
    answers: 
    - answer: "They share their experience and explain their role"
      hint: "They give at least one complete example about teamwork and their role"
      score: "2"
    - answer: "They share their experience, but don't tell their role"
      hint: "They give one or several examples of their previous experience, but don't mention their role in it"
      score: "1"
    - answer: "Incomplete or short answer / No experience"
      hint: "If they give an incomplete answer or finish it in one sentence or two, or they say they have no experience"
      score: "0"
   leadership:
    question: "If you were to implement the application described in the previous question, what would be your roadmap?"
    max_score: "3"
    answers:
    - answer: "They provide steps that can help them reach their goals"
      hint: "If they describe the roadmap in details and provide steps that will be able to follow in order to reach their goals"
      score: "3"
    - answer: "They give a common roadmap, but relate it to their application"
      hint: "They provide a roadmap like 'learn, code and test', but mention the steps related to their own project. Example: Building the Gui framework for the app, design and testing the interface"
      score: "2"
    - answer: "They provide logical, but not very detailed roadmap"
      hint: "Their roadmap is not very detailed, but the steps are logical and in order."
      score: "2"
    - answer: "They provide only basic info, with no detailed steps"
      hint: "If they give some general overview of their roadmap, without detailed steps or logical order"
      score: "1"
    - answer: "They give a generic roadmap that could be applied to any project"
      hint: "If they give some general steps, but nothing specific for their project. Example: learn, implement, test etc."
      score: "1"
    - answer: "They mention the name of the approach they will use with no other specifics"
      hint: "They give the name of the approach they want to use (like Agile), but don't give any details of how it is related with their project"
      score: "1"
    - answer: "They don't provide any roadmap"
      hint: "If they say they don't know it yet, or that it will be done with mentor guidance."
      score: "0"
    - answer: "They explain their application once again"
      hint: "If instead of giving a roadmap, they explain what their application would do all over again."
      score: "0"
    - answer: "They have provided a copied roadmap"
      hint: "If it feels like their roadmap is copied from some project. Example: it contains steps of marketing and deployment, or others which don’t actually belong there."
      score: "0"
    - answer: "Their roadmap doesn't have actual steps"
      hint: "If they only state that they will decide the workflow and requirements of the application, or they just mention the timeline, without stating the steps."
      score: "0"
 experience:
  question: "Tell us about your previous experience. What projects have you been working on? What was your role? What programming language did you use?"
  max_score: "2"
  answers: 
  - answer: "They have completed a project"
    hint: "If they have completed a project on their own or as part of GSOC, google code in, or in a group and did a meaningful part of it"
    score: "2"
  - answer: "They mention some project they have worked on, without explaining their role"
    hint: "If the scolar shares her previous experience without giving any specifics of what her role was in it"
    score: "1"
  - answer: "They only provide a github/blog link"
    hint: "They don't give any description of their previous experience, only share a link of their github profile or blog"
    score: "1"
  - answer: "Too many languages with no specified experience"
    hint: "If they mention too many laguages, with no projects listed to cover that."
    score: "0"
  - answer: "Described projects were never completed"
    hint: "If you find out that the described projects were never completed"
    score: "0"
 soundness:
  question: ""
  max_score: "2"
  answers:
  - answer: "They overestimated the time they can dedicate on the program"
    hint: "If they state they can put in more than 7 hours of work, even though they have a job/school and/or other responsibilities which involves them full time"
    score: "1"
  - answer: "They hide their real experience"
    hint: "If they state they don't know some language confidently, but you can tell from their application that they should"
    score: "1"
